
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres@db:5432/hello_world?sslmode=disable

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: hello_world
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root
    ports:
      - "5432:5432"
